services:
  fast-inspection-backoffice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fast-inspection-backoffice
    ports:
      - "3010:3010"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://66.55.75.130:3000/}
      - AUTH_SECRET=${AUTH_SECRET:-kagkhasghdgakjdghakghdkajgdkjasgdkagsdjgasjgdasdkgajdgaksd}
      - NODE_ENV=production
      - AUTH_MODE=${AUTH_MODE:-dev}
    restart: unless-stopped
    networks:
      - fast_inspection_network

networks:
  fast_inspection_network:
    name: fast_inspection_network